apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
        - name: container3
          image: image2
